"""Closed vocabularies for the intake domain. Everything downstream keys off these."""

from __future__ import annotations

from enum import StrEnum


class CaseState(StrEnum):
    CREATED = "CREATED"
    ANNOUNCED = "ANNOUNCED"  # pre-notification accepted, shipment not yet arrived (ISBER L4.2, CAP BAP.13200)
    RECEIVED = "RECEIVED"  # physical custody taken and condition recorded; tubes not yet reconciled
    VERIFYING = "VERIFYING"
    WAITING_FOR_EVIDENCE = "WAITING_FOR_EVIDENCE"
    NEEDS_HUMAN_DECISION = "NEEDS_HUMAN_DECISION"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class SampleState(StrEnum):
    PENDING = "PENDING"
    WAITING_FOR_EVIDENCE = "WAITING_FOR_EVIDENCE"
    NEEDS_HUMAN_DECISION = "NEEDS_HUMAN_DECISION"
    ACCEPTED = "ACCEPTED"
    ACCEPTED_WITH_EXCEPTION = "ACCEPTED_WITH_EXCEPTION"
    QUARANTINED = "QUARANTINED"
    REJECTED = "REJECTED"  # only ever reached by an authorised human decision, never automatically
    ERROR = "ERROR"


# QUARANTINED is terminal *for the intake case*: the intake decision has been made, and the shipment is
# finished. Resolving the hold is a separate, later review (see SAMPLE_TRANSITIONS), which reopens the case.
TERMINAL_SAMPLE_STATES: frozenset[SampleState] = frozenset(
    {
        SampleState.ACCEPTED,
        SampleState.ACCEPTED_WITH_EXCEPTION,
        SampleState.QUARANTINED,
        SampleState.REJECTED,
    }
)
TERMINAL_CASE_STATES: frozenset[CaseState] = frozenset({CaseState.COMPLETED, CaseState.FAILED})


class CheckStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNAVAILABLE = "UNAVAILABLE"
    AMBIGUOUS = "AMBIGUOUS"
    ERROR = "ERROR"


class CheckCategory(StrEnum):
    IDENTITY_MATCH = "IDENTITY_MATCH"
    MANIFEST_MATCH = "MANIFEST_MATCH"
    PROTOCOL_ELIGIBILITY = "PROTOCOL_ELIGIBILITY"
    CONSENT_VALIDITY = "CONSENT_VALIDITY"
    TEMPERATURE_REQUIREMENT = "TEMPERATURE_REQUIREMENT"
    CHAIN_OF_CUSTODY = "CHAIN_OF_CUSTODY"
    LIMS_RECONCILIATION = "LIMS_RECONCILIATION"


REQUIRED_CHECKS: tuple[CheckCategory, ...] = tuple(CheckCategory)


class PolicyDecision(StrEnum):
    ALLOWED = "ALLOWED"
    DENIED = "DENIED"
    HUMAN_DECISION_REQUIRED = "HUMAN_DECISION_REQUIRED"
    WAITING_FOR_EVIDENCE = "WAITING_FOR_EVIDENCE"
    SYSTEM_ERROR = "SYSTEM_ERROR"


class Disposition(StrEnum):
    ACCEPT = "ACCEPT"
    ACCEPT_WITH_EXCEPTION = "ACCEPT_WITH_EXCEPTION"
    QUARANTINE = "QUARANTINE"
    REJECT = "REJECT"


class HumanOption(StrEnum):
    QUARANTINE = "QUARANTINE"
    APPROVE_EXCEPTION = "APPROVE_EXCEPTION"
    REJECT = "REJECT"


class ActorType(StrEnum):
    SYSTEM = "SYSTEM"
    AGENT = "AGENT"
    HUMAN = "HUMAN"
    SENDER = "SENDER"


class ActorRole(StrEnum):
    SYSTEM = "SYSTEM"
    AGENT = "AGENT"
    COORDINATOR = "COORDINATOR"
    PRINCIPAL_INVESTIGATOR = "PRINCIPAL_INVESTIGATOR"
    QA_REVIEWER = "QA_REVIEWER"
    SITE_CONTACT = "SITE_CONTACT"
    UNKNOWN = "UNKNOWN"


class PackageCondition(StrEnum):
    """Three-state grading used on receipt (NCI BPV discrepancy checklist OP-0014-W1-F1)."""

    ACCEPTABLE = "ACCEPTABLE"
    DAMAGED_USABLE = "DAMAGED_USABLE"
    DAMAGED_NOT_USABLE = "DAMAGED_NOT_USABLE"


class ReceivedQuality(StrEnum):
    """How a specimen looked when it was received, a permanent property of that specimen.

    The vocabulary is OpenSpecimen's Received Event quality list, because it is what biobank staff already
    read and write. Note this is per-specimen and distinct from the condition of the package it arrived in:
    a box can be intact and one tube inside it still be thawed.
    """

    ACCEPTABLE = "ACCEPTABLE"
    THAWED = "THAWED"
    QUANTITY_NOT_SUFFICIENT = "QUANTITY_NOT_SUFFICIENT"
    CLOTTED = "CLOTTED"
    HEMOLYZED = "HEMOLYZED"
    LIPEMIC = "LIPEMIC"
    DAMAGED = "DAMAGED"
    UNACCEPTABLE = "UNACCEPTABLE"


class ScanOutcome(StrEnum):
    """Outcome of one scan against the manifest-derived expected rows (Nautilus pattern)."""

    MATCHED = "MATCHED"  # exact match to an expected row
    NEAR_MATCH = "NEAR_MATCH"  # confusable-glyph match; needs sender confirmation
    UNEXPECTED = "UNEXPECTED"  # scanned but not on the manifest
    DUPLICATE = "DUPLICATE"  # this row was already scanned


class ArtifactType(StrEnum):
    SHIPMENT_NOTICE = "SHIPMENT_NOTICE"
    MANIFEST = "MANIFEST"
    SCANNER_EXPORT = "SCANNER_EXPORT"
    TEMPERATURE_LOG = "TEMPERATURE_LOG"
    PROTOCOL = "PROTOCOL"
    CONSENT_RECORDS = "CONSENT_RECORDS"
    CONSENT_ADDENDUM = "CONSENT_ADDENDUM"
    SENDER_ATTESTATION = "SENDER_ATTESTATION"
    CUSTODY_LOG = "CUSTODY_LOG"
    LIMS_SNAPSHOT = "LIMS_SNAPSHOT"
    AUDIT_REPORT = "AUDIT_REPORT"


class ArtifactValidation(StrEnum):
    PENDING = "PENDING"
    VALID = "VALID"
    REJECTED = "REJECTED"


class RequirementType(StrEnum):
    CONSENT_ADDENDUM = "CONSENT_ADDENDUM"
    MANIFEST_CORRECTION = "MANIFEST_CORRECTION"
    CUSTODY_RECORD = "CUSTODY_RECORD"  # an event missing from a custody log that was supplied
    # Whole documents the shipment arrived without. These belong to the shipment, not to any one
    # sample, so they are asked for once rather than twelve times.
    CONSENT_REGISTRY = "CONSENT_REGISTRY"
    CUSTODY_LOG = "CUSTODY_LOG"


class EvidenceRequestStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SATISFIED = "SATISFIED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class AuditKind(StrEnum):
    DOMAIN_EFFECT = "DOMAIN_EFFECT"  # a logical business event; must happen exactly once
    TOOL_ATTEMPT = "TOOL_ATTEMPT"  # an execution attempt; may legitimately repeat (at-least-once)
    TELEMETRY = "TELEMETRY"  # model calls, invocation boundaries, timings


class InvocationEventType(StrEnum):
    CASE_READY = "CASE_READY"
    EVIDENCE_RECEIVED = "EVIDENCE_RECEIVED"
    HUMAN_DECISION_RECEIVED = "HUMAN_DECISION_RECEIVED"
    RETRY_REQUESTED = "RETRY_REQUESTED"


class AuditEventType(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    SHIPMENT_ANNOUNCED = "SHIPMENT_ANNOUNCED"
    SHIPMENT_RECEIVED = "SHIPMENT_RECEIVED"
    SCAN_RECORDED = "SCAN_RECORDED"
    SPECIMEN_QUALITY_RECORDED = "SPECIMEN_QUALITY_RECORDED"
    STAGING_BATCH_COMMITTED = "STAGING_BATCH_COMMITTED"
    STUDY_SAVED = "STUDY_SAVED"
    CONTACT_REGISTERED = "CONTACT_REGISTERED"
    CASE_TRANSITION = "CASE_TRANSITION"
    SAMPLE_TRANSITION = "SAMPLE_TRANSITION"
    CHECK_RECORDED = "CHECK_RECORDED"
    POLICY_EVALUATED = "POLICY_EVALUATED"
    LIMS_WRITE = "LIMS_WRITE"
    LIMS_WRITE_REFUSED = "LIMS_WRITE_REFUSED"
    EVIDENCE_REQUEST_SENT = "EVIDENCE_REQUEST_SENT"
    EVIDENCE_RECEIVED = "EVIDENCE_RECEIVED"
    EVIDENCE_REJECTED = "EVIDENCE_REJECTED"
    EVIDENCE_REQUEST_SATISFIED = "EVIDENCE_REQUEST_SATISFIED"
    PENDING_DECISION_CREATED = "PENDING_DECISION_CREATED"
    HUMAN_DECISION_RECORDED = "HUMAN_DECISION_RECORDED"
    HUMAN_DECISION_APPLIED = "HUMAN_DECISION_APPLIED"
    QUARANTINE_REVIEW_OPENED = "QUARANTINE_REVIEW_OPENED"
    INVALIDATION_PLAN_CREATED = "INVALIDATION_PLAN_CREATED"
    INVALIDATION_PLAN_APPLIED = "INVALIDATION_PLAN_APPLIED"
    RETRY_REQUESTED = "RETRY_REQUESTED"
    RETRY_REFUSED = "RETRY_REFUSED"
    TOOL_ATTEMPT = "TOOL_ATTEMPT"
    TOOL_RESULT = "TOOL_RESULT"
    MODEL_CALL = "MODEL_CALL"
    INVOCATION_STARTED = "INVOCATION_STARTED"
    INVOCATION_FINISHED = "INVOCATION_FINISHED"
    INTERVENTION_DENIED = "INTERVENTION_DENIED"
    OPERATION_REPLAYED = "OPERATION_REPLAYED"
    OPERATION_REJECTED = "OPERATION_REJECTED"
    CASE_FINALIZED = "CASE_FINALIZED"


class ReasonCode(StrEnum):
    # verification outcomes
    ALL_CHECKS_PASS = "ALL_CHECKS_PASS"
    MANIFEST_IDENTIFIER_NEAR_MATCH = "MANIFEST_IDENTIFIER_NEAR_MATCH"
    MANIFEST_ROW_MISSING = "MANIFEST_ROW_MISSING"
    MANIFEST_FIELD_MISMATCH = "MANIFEST_FIELD_MISMATCH"
    LABEL_UNREADABLE = "LABEL_UNREADABLE"
    LABEL_DUPLICATE = "LABEL_DUPLICATE"
    CONSENT_ADDENDUM_MISSING = "CONSENT_ADDENDUM_MISSING"
    CONSENT_RECORD_MISSING = "CONSENT_RECORD_MISSING"
    CONSENT_INVALID = "CONSENT_INVALID"
    BARCODE_COLLISION = "BARCODE_COLLISION"
    LIMS_RECORD_MISSING = "LIMS_RECORD_MISSING"
    TEMPERATURE_EXCURSION = "TEMPERATURE_EXCURSION"
    TEMPERATURE_LOG_MISSING = "TEMPERATURE_LOG_MISSING"
    TEMPERATURE_LOG_MALFORMED = "TEMPERATURE_LOG_MALFORMED"
    CUSTODY_EVENT_MISSING = "CUSTODY_EVENT_MISSING"
    CUSTODY_ORDER_INVALID = "CUSTODY_ORDER_INVALID"
    PROTOCOL_MISMATCH = "PROTOCOL_MISMATCH"
    # evidence / communications
    UNAUTHORIZED_ATTESTATION = "UNAUTHORIZED_ATTESTATION"
    EVIDENCE_CHECKSUM_MISMATCH = "EVIDENCE_CHECKSUM_MISMATCH"
    EVIDENCE_UNMATCHED = "EVIDENCE_UNMATCHED"
    EVIDENCE_CONTRADICTORY = "EVIDENCE_CONTRADICTORY"
    RECIPIENT_NOT_VERIFIED = "RECIPIENT_NOT_VERIFIED"
    DUPLICATE_EVIDENCE_REQUEST = "DUPLICATE_EVIDENCE_REQUEST"
    REQUEST_NOT_ACTIVE = "REQUEST_NOT_ACTIVE"
    UPLOAD_TOKEN_INVALID = "UPLOAD_TOKEN_INVALID"
    # policy / authority
    HUMAN_AUTHORITY_REQUIRED = "HUMAN_AUTHORITY_REQUIRED"
    HUMAN_DECISION_APPLIED = "HUMAN_DECISION_APPLIED"
    INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE"
    EXCEPTION_NOT_PERMITTED = "EXCEPTION_NOT_PERMITTED"
    DISPOSITION_NOT_IMPLEMENTED = "DISPOSITION_NOT_IMPLEMENTED"
    REQUIRED_CHECK_MISSING = "REQUIRED_CHECK_MISSING"
    REQUIRED_EVIDENCE_NOT_SUPPLIED = "REQUIRED_EVIDENCE_NOT_SUPPLIED"
    EVIDENCE_RECOVERY_IN_PROGRESS = "EVIDENCE_RECOVERY_IN_PROGRESS"
    STALE_POLICY_EVALUATION = "STALE_POLICY_EVALUATION"
    EVALUATION_CONSUMED = "EVALUATION_CONSUMED"
    INVALIDATION_PLAN_INVALID = "INVALIDATION_PLAN_INVALID"
    ASSOCIATION_REFUTED = "ASSOCIATION_REFUTED"
    PROVISIONAL_RESULT = "PROVISIONAL_RESULT"
    RETRY_NOT_PERMITTED = "RETRY_NOT_PERMITTED"
    RETRY_BUDGET_EXHAUSTED = "RETRY_BUDGET_EXHAUSTED"
    TOOL_FAILURE_TRANSIENT = "TOOL_FAILURE_TRANSIENT"
    TOOL_BUDGET_EXCEEDED = "TOOL_BUDGET_EXCEEDED"
    INTERVENTION_DENIED = "INTERVENTION_DENIED"
    OPERATION_SCOPE_MISMATCH = "OPERATION_SCOPE_MISMATCH"
    # system / consistency
    DUPLICATE_OPERATION = "DUPLICATE_OPERATION"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    CASE_FINALIZED = "CASE_FINALIZED"
    VERSION_CONFLICT = "VERSION_CONFLICT"
    NOT_FOUND = "NOT_FOUND"
    CHECK_ERROR = "CHECK_ERROR"
    # intake ramp
    MANIFEST_REJECTED = "MANIFEST_REJECTED"
    QUARANTINE_REVIEW_OPENED = "QUARANTINE_REVIEW_OPENED"
    SPECIMEN_REJECTED = "SPECIMEN_REJECTED"
    SPECIMEN_TYPE_NOT_IN_STUDY = "SPECIMEN_TYPE_NOT_IN_STUDY"
    SHIPMENT_ALREADY_ANNOUNCED = "SHIPMENT_ALREADY_ANNOUNCED"
    PACKAGE_DAMAGED = "PACKAGE_DAMAGED"
    SCAN_UNEXPECTED_SPECIMEN = "SCAN_UNEXPECTED_SPECIMEN"
    SCAN_DUPLICATE = "SCAN_DUPLICATE"
    SPECIMEN_QUALITY_NOT_ACCEPTABLE = "SPECIMEN_QUALITY_NOT_ACCEPTABLE"
    SPECIMEN_NOT_RECEIVED = "SPECIMEN_NOT_RECEIVED"
    PARTIAL_RECEIPT = "PARTIAL_RECEIPT"
